pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/doanvanminhbk27/hello_jenkins.git'
            }
        }
    }
}
